import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const storeApp = readFileSync(join(root, 'store-app.js'), 'utf8');
const deliveryNote = readFileSync(join(root, 'store-delivery-note.js'), 'utf8');
const storeStyle = readFileSync(join(root, 'store-style.css'), 'utf8');
const afterSales = readFileSync(join(root, 'store-after-sales.js'), 'utf8');
const storeHtml = readFileSync(join(root, 'store.html'), 'utf8');

assert.ok(storeApp.includes('function orderDetailDisplayLabel(product,item)'), 'order detail should derive product labels from spec/flavor');
assert.ok(storeApp.includes('function orderDetailGroupKey(product,item)'), 'order detail should group rows by the display spec/flavor key');
assert.ok(storeApp.includes('const key=orderDetailGroupKey(p,it)'), 'order detail aggregation should use the spec/flavor display key instead of barcode');
assert.ok(storeApp.includes('product_name:orderDetailDisplayLabel(p,it)'), 'order detail rows should store the spec/flavor label');
assert.ok(!storeApp.includes('product_name:it.product_name||p.product_name||bc'), 'order detail should not fall back to product_name as the primary detail title');
assert.ok(storeApp.includes('order-detail-list'), 'order detail should render rows inside a unified detail list');
assert.ok(storeApp.includes('order-detail-row'), 'order detail should use a dedicated row class instead of generic item cards');
assert.ok(storeApp.includes('order-detail-title'), 'order detail should use a dedicated title class');
assert.ok(storeApp.includes('order-detail-line'), 'order detail should use a dedicated detail line class');
assert.ok(storeStyle.includes('.order-detail-list'), 'order detail list should be styled centrally');
assert.ok(storeStyle.includes('.order-detail-row'), 'order detail row should be styled centrally');
assert.ok(afterSales.includes('order-detail-row'), 'after-sales detail override should use the same detail row class');
assert.ok(afterSales.includes('orderDetailDisplayLabel(p,{barcode})'), 'after-sales-only rows should reuse spec/flavor detail labels');
assert.ok(storeHtml.indexOf('store-app.js') < storeHtml.indexOf('store-delivery-note.js'), 'delivery note module should load after store app helpers');
assert.ok(storeHtml.indexOf('store-delivery-note.js') < storeHtml.indexOf('store-after-sales.js'), 'delivery note module should load before after-sales overrides');
assert.ok(!storeApp.includes('async function getDeliveryNoteRows(orderNo)'), 'store app should not own delivery note aggregation');
assert.ok(!storeApp.includes('function buildDeliveryNoteHtml'), 'store app should not own delivery note template rendering');
assert.ok(!storeApp.includes('async function generateDeliveryNote(orderNo,orderDate)'), 'store app should not own delivery note generation');
assert.ok(!storeApp.includes('function downloadDeliveryImage(imgUrl,fileName)'), 'store app should not own delivery note downloads');
assert.ok(deliveryNote.includes('function downloadDeliveryImage(imgUrl,fileName)'), 'delivery note should use a direct download helper');
assert.ok(deliveryNote.includes("const link=document.createElement('a')"), 'direct download should create a temporary anchor');
assert.ok(deliveryNote.includes('link.download=esc(fileName)'), 'direct download should set the image filename');
assert.ok(deliveryNote.includes('link.click()'), 'direct download should click the temporary anchor');
assert.ok(deliveryNote.includes('downloadDeliveryImage(imgUrl,'), 'generateDeliveryNote should download immediately after rendering');
assert.ok(!deliveryNote.includes('showDeliveryImage'), 'delivery note should not show or call an image preview overlay');
assert.ok(!deliveryNote.includes('function openDeliveryImageFullscreen'), 'delivery note should not expose fullscreen preview');
assert.ok(!deliveryNote.includes('delivery-note-overlay'), 'delivery note should not render an overlay with the image URL');
assert.ok(!deliveryNote.includes('delivery-note-preview-img'), 'delivery note should not render a preview image that can be screenshotted with page URL');
assert.ok(storeStyle.includes('.delivery-note-capture-wrap{position:fixed;left:-10000px;top:0'), 'delivery note capture wrapper should render offscreen to prevent flicker');
assert.ok(!storeStyle.includes('.delivery-note-capture-wrap{position:fixed;left:0;top:0'), 'delivery note capture wrapper should not be placed at the visible viewport origin');
assert.ok(storeApp.includes('history-item-actions'), 'order history cards should use an action row for detail and delivery-note actions');
assert.ok(storeApp.includes('delivery-note-btn delivery-note-btn-primary'), 'delivery note buttons should have a stronger primary style');
assert.ok(storeApp.includes('detail-action-row'), 'order detail actions should use a dedicated action row');
assert.ok(storeApp.includes('detail-delivery-action'), 'order detail should promote delivery-note generation as the primary action');
assert.ok(deliveryNote.includes('function buildDeliveryNoteHtml({storeName,rows,totalAmount,employeeName,orderDate})'), 'delivery note HTML should receive the order date');
assert.ok(deliveryNote.includes('delivery-note-date'), 'delivery note image should render the order date');
assert.ok(deliveryNote.includes('orderDate:orderDate||'), 'generateDeliveryNote should pass the order date into the rendered note');
assert.ok(storeStyle.includes('.history-item-actions'), 'history action row should be styled');
assert.ok(storeStyle.includes('.delivery-note-btn-primary'), 'primary delivery note button should be styled');
assert.ok(storeStyle.includes('.detail-delivery-action'), 'detail delivery note action should be styled as prominent');
assert.ok(storeApp.includes('detail-summary-actions'), 'order detail should keep the amount and delivery-note action on the same row');
assert.ok(storeApp.includes('detail-danger-action'), 'order detail delete action should be visually separated on the right');
assert.ok(storeApp.includes('history-item-compact'), 'history cards should use a compact layout');
assert.ok(storeApp.includes('history-item-meta'), 'history card item count should use a dedicated compact meta row');
assert.ok(!storeApp.includes('\u67e5\u770b\u8be6\u60c5'), 'history cards should remove view-detail wording');
assert.ok(!storeApp.includes('\u4fee\u6539\u8ba2\u5355'), 'detail edit button should use shorter wording');
assert.ok(!storeApp.includes('\u5220\u9664\u8ba2\u5355'), 'detail delete button should use shorter wording');
assert.ok(storeStyle.includes('.history-item-compact'), 'compact history card style should be present');
assert.ok(storeStyle.includes('.detail-summary-actions'), 'detail summary action row style should be present');
assert.ok(storeStyle.includes('.detail-danger-action'), 'detail delete action should have a right-aligned style');
assert.ok(storeStyle.includes('.delivery-note-date'), 'delivery note date should be styled in the exported sheet');
assert.ok(afterSales.includes('history-item-actions'), 'after-sales history override should keep the stronger delivery-note action row');
assert.ok(afterSales.includes('detail-action-row'), 'after-sales detail override should keep the promoted delivery-note action');
assert.ok(afterSales.includes('delivery-note-btn delivery-note-btn-primary'), 'after-sales overrides should use the primary delivery-note button style');
assert.ok(afterSales.includes('detail-summary-actions'), 'after-sales detail override should keep delivery-note action beside the amount');
assert.ok(afterSales.includes('history-item-compact'), 'after-sales history override should use compact history cards');
assert.ok(!afterSales.includes('\u67e5\u770b\u8be6\u60c5'), 'after-sales history override should remove view-detail wording');
assert.ok(!afterSales.includes('\u4fee\u6539\u8ba2\u5355'), 'after-sales detail edit button should use shorter wording');
assert.ok(!afterSales.includes('\u5220\u9664\u8ba2\u5355'), 'after-sales detail delete button should use shorter wording');
